//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.07 at 10:58:45 AM PDT 
//


package com.fileobj.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BugCollection element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="BugCollection">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Project"/>
 *           &lt;element ref="{}BugInstance" maxOccurs="unbounded"/>
 *           &lt;element ref="{}Errors"/>
 *           &lt;element ref="{}FindBugsSummary"/>
 *           &lt;element ref="{}ClassFeatures"/>
 *           &lt;element ref="{}History"/>
 *         &lt;/sequence>
 *         &lt;attribute name="analysisTimestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="release" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project",
    "bugInstance",
    "errors",
    "findBugsSummary",
    "classFeatures",
    "history"
})
@XmlRootElement(name = "BugCollection")
public class BugCollection {

    @XmlElement(name = "Project")
    protected Project project;
    @XmlElement(name = "BugInstance")
    protected List<BugInstance> bugInstance;
    @XmlElement(name = "Errors")
    protected Errors errors;
    @XmlElement(name = "FindBugsSummary")
    protected FindBugsSummary findBugsSummary;
    @XmlElement(name = "ClassFeatures")
    protected ClassFeatures classFeatures;
    @XmlElement(name = "History")
    protected History history;
    @XmlAttribute(required = true)
    protected BigInteger analysisTimestamp;
    @XmlAttribute(required = true)
    protected String release;
    @XmlAttribute(required = true)
    protected BigInteger sequence;
    @XmlAttribute(required = true)
    protected BigInteger timestamp;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public Project getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project }
     *     
     */
    public void setProject(Project value) {
        this.project = value;
    }

    /**
     * Gets the value of the bugInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bugInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBugInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BugInstance }
     * 
     * 
     */
    public List<BugInstance> getBugInstance() {
        if (bugInstance == null) {
            bugInstance = new ArrayList<BugInstance>();
        }
        return this.bugInstance;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link Errors }
     *     
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Errors }
     *     
     */
    public void setErrors(Errors value) {
        this.errors = value;
    }

    /**
     * Gets the value of the findBugsSummary property.
     * 
     * @return
     *     possible object is
     *     {@link FindBugsSummary }
     *     
     */
    public FindBugsSummary getFindBugsSummary() {
        return findBugsSummary;
    }

    /**
     * Sets the value of the findBugsSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FindBugsSummary }
     *     
     */
    public void setFindBugsSummary(FindBugsSummary value) {
        this.findBugsSummary = value;
    }

    /**
     * Gets the value of the classFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link ClassFeatures }
     *     
     */
    public ClassFeatures getClassFeatures() {
        return classFeatures;
    }

    /**
     * Sets the value of the classFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassFeatures }
     *     
     */
    public void setClassFeatures(ClassFeatures value) {
        this.classFeatures = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the analysisTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnalysisTimestamp() {
        return analysisTimestamp;
    }

    /**
     * Sets the value of the analysisTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnalysisTimestamp(BigInteger value) {
        this.analysisTimestamp = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelease(String value) {
        this.release = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
