//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.07 at 10:58:45 AM PDT 
//


package com.fileobj.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassStats element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ClassStats">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="bugs" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="interface" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *         &lt;attribute name="priority_2" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="priority_3" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="priority_4" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ClassStats")
public class ClassStats {

    @XmlAttribute(required = true)
    protected BigInteger bugs;
    @XmlAttribute(name = "class", required = true)
    protected String clazz;
    @XmlAttribute(name = "interface", required = true)
    protected boolean _interface;
    @XmlAttribute(name = "priority_2")
    protected BigInteger priority2;
    @XmlAttribute(name = "priority_3")
    protected BigInteger priority3;
    @XmlAttribute(name = "priority_4")
    protected BigInteger priority4;
    @XmlAttribute(required = true)
    protected BigInteger size;

    /**
     * Gets the value of the bugs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBugs() {
        return bugs;
    }

    /**
     * Sets the value of the bugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBugs(BigInteger value) {
        this.bugs = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the interface property.
     * 
     */
    public boolean isInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     */
    public void setInterface(boolean value) {
        this._interface = value;
    }

    /**
     * Gets the value of the priority2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority2() {
        return priority2;
    }

    /**
     * Sets the value of the priority2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority2(BigInteger value) {
        this.priority2 = value;
    }

    /**
     * Gets the value of the priority3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority3() {
        return priority3;
    }

    /**
     * Sets the value of the priority3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority3(BigInteger value) {
        this.priority3 = value;
    }

    /**
     * Gets the value of the priority4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority4() {
        return priority4;
    }

    /**
     * Sets the value of the priority4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority4(BigInteger value) {
        this.priority4 = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

}
