//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.07 at 10:58:45 AM PDT 
//


package com.fileobj.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sampullara.findbugs.om package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SrcDir_QNAME = new QName("", "SrcDir");
    private final static QName _MissingClass_QNAME = new QName("", "MissingClass");
    private final static QName _AuxClasspathEntry_QNAME = new QName("", "AuxClasspathEntry");
    private final static QName _Jar_QNAME = new QName("", "Jar");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sampullara.findbugs.om
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link BugInstance }
     * 
     */
    public BugInstance createBugInstance() {
        return new BugInstance();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link SourceLine }
     * 
     */
    public SourceLine createSourceLine() {
        return new SourceLine();
    }

    /**
     * Create an instance of {@link FindBugsSummary }
     * 
     */
    public FindBugsSummary createFindBugsSummary() {
        return new FindBugsSummary();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link ClassStats }
     * 
     */
    public ClassStats createClassStats() {
        return new ClassStats();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link PackageStats }
     * 
     */
    public PackageStats createPackageStats() {
        return new PackageStats();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link LocalVariable }
     * 
     */
    public LocalVariable createLocalVariable() {
        return new LocalVariable();
    }

    /**
     * Create an instance of {@link ClassFeatures }
     * 
     */
    public ClassFeatures createClassFeatures() {
        return new ClassFeatures();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link BugCollection }
     * 
     */
    public BugCollection createBugCollection() {
        return new BugCollection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SrcDir")
    public JAXBElement<String> createSrcDir(String value) {
        return new JAXBElement<String>(_SrcDir_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MissingClass")
    public JAXBElement<String> createMissingClass(String value) {
        return new JAXBElement<String>(_MissingClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuxClasspathEntry")
    public JAXBElement<String> createAuxClasspathEntry(String value) {
        return new JAXBElement<String>(_AuxClasspathEntry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jar")
    public JAXBElement<String> createJar(String value) {
        return new JAXBElement<String>(_Jar_QNAME, String.class, null, value);
    }

}
