//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.07 at 10:58:45 AM PDT 
//


package com.fileobj.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PackageStats element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="PackageStats">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}ClassStats" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;attribute name="package" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *         &lt;attribute name="priority_2" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="priority_3" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="priority_4" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="total_bugs" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="total_size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="total_types" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classStats"
})
@XmlRootElement(name = "PackageStats")
public class PackageStats {

    @XmlElement(name = "ClassStats")
    protected List<ClassStats> classStats;
    @XmlAttribute(name = "package", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String _package;
    @XmlAttribute(name = "priority_2")
    protected BigInteger priority2;
    @XmlAttribute(name = "priority_3")
    protected BigInteger priority3;
    @XmlAttribute(name = "priority_4")
    protected BigInteger priority4;
    @XmlAttribute(name = "total_bugs", required = true)
    protected BigInteger totalBugs;
    @XmlAttribute(name = "total_size", required = true)
    protected BigInteger totalSize;
    @XmlAttribute(name = "total_types", required = true)
    protected BigInteger totalTypes;

    /**
     * Gets the value of the classStats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classStats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassStats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassStats }
     * 
     * 
     */
    public List<ClassStats> getClassStats() {
        if (classStats == null) {
            classStats = new ArrayList<ClassStats>();
        }
        return this.classStats;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the priority2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority2() {
        return priority2;
    }

    /**
     * Sets the value of the priority2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority2(BigInteger value) {
        this.priority2 = value;
    }

    /**
     * Gets the value of the priority3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority3() {
        return priority3;
    }

    /**
     * Sets the value of the priority3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority3(BigInteger value) {
        this.priority3 = value;
    }

    /**
     * Gets the value of the priority4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority4() {
        return priority4;
    }

    /**
     * Sets the value of the priority4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority4(BigInteger value) {
        this.priority4 = value;
    }

    /**
     * Gets the value of the totalBugs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalBugs() {
        return totalBugs;
    }

    /**
     * Sets the value of the totalBugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalBugs(BigInteger value) {
        this.totalBugs = value;
    }

    /**
     * Gets the value of the totalSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalSize() {
        return totalSize;
    }

    /**
     * Sets the value of the totalSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalSize(BigInteger value) {
        this.totalSize = value;
    }

    /**
     * Gets the value of the totalTypes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalTypes() {
        return totalTypes;
    }

    /**
     * Sets the value of the totalTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalTypes(BigInteger value) {
        this.totalTypes = value;
    }

}
