//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.07 at 10:58:45 AM PDT 
//


package com.fileobj.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Project element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Project">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Jar"/>
 *           &lt;element ref="{}AuxClasspathEntry" maxOccurs="unbounded"/>
 *           &lt;element ref="{}SrcDir"/>
 *         &lt;/sequence>
 *         &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jar",
    "auxClasspathEntry",
    "srcDir"
})
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "Jar")
    protected String jar;
    @XmlElement(name = "AuxClasspathEntry")
    protected List<String> auxClasspathEntry;
    @XmlElement(name = "SrcDir")
    protected String srcDir;
    @XmlAttribute(required = true)
    protected String filename;

    /**
     * Gets the value of the jar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJar() {
        return jar;
    }

    /**
     * Sets the value of the jar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJar(String value) {
        this.jar = value;
    }

    /**
     * Gets the value of the auxClasspathEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auxClasspathEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuxClasspathEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuxClasspathEntry() {
        if (auxClasspathEntry == null) {
            auxClasspathEntry = new ArrayList<String>();
        }
        return this.auxClasspathEntry;
    }

    /**
     * Gets the value of the srcDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcDir() {
        return srcDir;
    }

    /**
     * Sets the value of the srcDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcDir(String value) {
        this.srcDir = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

}
